stemmer.lo: /usr/src/stemmer-php/stemmer.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/usr/src/stemmer-php $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /usr/src/stemmer-php/stemmer.c -o stemmer.lo 
$(phplibdir)/stemmer.la: ./stemmer.la
	$(LIBTOOL) --mode=install cp ./stemmer.la $(phplibdir)

./stemmer.la: $(shared_objects_stemmer) $(STEMMER_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS) -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_stemmer) $(STEMMER_SHARED_LIBADD)

